import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title:{
    default: "Home |  Alphabyte Electronics",
    template:"%s |  Alphabyte Electronics"
  },
  description: "Generated by Alphabyte Electronics",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <div className="sm:relative h-0 w-0"> */}
          {/* <div className="sm:absolute sm:h-[150px] sm:w-[150px] md:h-[850px] md:w-[850px] -left-[425px] -top-[425px]  rounded-full border-[4rem] border-green-background border-solid bg-transparent blur-[100px]"></div> */}
          {/* <div className="sm:absolute sm:h-0 sm:w-0  md:h-[475px] md:w-[475px] -right-[15rem] -top-[15rem]  rounded-full bg-gradient-to-tr from-green-li_background-main blur-[100px]"></div> */}
        {/* </div> */}
        {/* <div className="sm:relative ">
          <div className="sm:absolute sm:h-0 sm:w-0  md:h-[475px] md:w-[475px] -right-[15rem] -top-[15rem]  rounded-full bg-gradient-to-tr from-green-li_background-main blur-[100px]"></div>
        </div> */}
        {/* <header>
          <Header />
        </header> */}

        {children}
        {/* <footer
          style={{
            // backgroundColor:"lightblue" ,
            padding: "1rem",
            color: "gray",
            border: "1px solid #ffffff",
          }}
        >
          <div className="container mx-auto">Footer</div>
        </footer> */}
      </body>
    </html>
  );
}
